[package]
name = "spinny"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.21.0", features = ["derive"] }
glam = "0.30.0"
image = "0.25.5"
pollster = "0.4.0"
tobj = "4.0.3"
wgpu = "24.0.1"
winit = {version = "0.30.9", features = ["rwh_05"]}
